# Generated by Django 4.0.6 on 2023-01-31 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre_song_creator_comment_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
