# Generated by Django 4.0.6 on 2023-02-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_song_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
