# Generated by Django 4.0.6 on 2023-02-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_song_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
    ]
