# Generated by Django 4.0.6 on 2023-02-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_editrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.song'),
        ),
    ]
