# Generated by Django 4.0.6 on 2023-02-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_editrequest_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='edit',
            field=models.TextField(default=None),
        ),
    ]
