# Generated by Django 4.0.6 on 2023-02-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_editrequest_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
