# Generated by Django 4.0.6 on 2023-02-24 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_editrequest_approved_editrequest_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='base.song'),
        ),
    ]
