# Generated by Django 4.0.6 on 2023-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_rating_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editrequest',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='editrequest',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
