# Generated by Django 4.0.6 on 2023-02-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_editrequest_options_editrequest_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editrequest',
            options={},
        ),
    ]
