# Generated by Django 4.0.6 on 2023-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_editrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editrequest',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
