# Generated by Django 4.0.6 on 2023-03-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.ImageField(default='no_img_artist.png', upload_to=''),
        ),
    ]
