# Generated by Django 4.0.6 on 2023-03-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_song_album_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_art',
            field=models.URLField(),
        ),
    ]
