# Generated by Django 4.0.6 on 2023-03-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_song_album_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_art',
        ),
    ]
